const PaymentService = (() => {
  const pay = (userId, amount, card) => { AuditService.log({userId,action:'PAYMENT_STARTED',module:'PAYMENTS',entityType:'PAYMENT',entityId:'',description:'Inició pago simulado'}); const digits=(card.number||'').replace(/\D/g,''); if(digits.length<13||digits.length>19||!/^[0-9]{3,4}$/.test(card.cvv||'')||!card.expiry) { AuditService.log({userId,action:'PAYMENT_FAILED',module:'PAYMENTS',entityType:'PAYMENT',entityId:'',description:'Pago simulado rechazado por formato'}); throw Error('No se pudo completar el pago simulado.'); } const payments=StorageService.getPayments(); const p={id:StorageService.generateId('PAY',payments), userId, amount, status:'APROBADO', method:'Tarjeta simulada', cardLast4:digits.slice(-4), createdAt:new Date().toISOString()}; payments.push(p); StorageService.savePayments(payments); AuditService.log({userId,action:'PAYMENT_APPROVED',module:'PAYMENTS',entityType:'PAYMENT',entityId:p.id,description:`Pago simulado aprobado ${p.id}`}); return p; };
  const find = id => StorageService.getPayments().find(p=>p.id===id);
  return {pay, find};
})();
const OrderService = (() => {
  const all = () => StorageService.getOrders();
  const find = id => all().find(o=>o.id===id);
  const checkout = (buyerId, card) => { const cart=CartService.totals(buyerId); if(!cart.items.length) throw Error('El carrito está vacío.'); AuditService.log({userId:buyerId,action:'CHECKOUT_STARTED',module:'ORDERS',entityType:'USER',entityId:buyerId,description:'Inició proceso de pago'}); const payment=PaymentService.pay(buyerId, cart.total, card); const orders=all(); const buyer=UserService.find(buyerId); const bySeller=cart.items.reduce((m,i)=>((m[i.sellerId]=m[i.sellerId]||[]).push(i),m),{}); const created=[]; Object.entries(bySeller).forEach(([sellerId,items])=>{ const subtotal=items.reduce((s,i)=>s+i.price*i.quantity,0); const o={id:StorageService.generateId('ORD',orders), buyerId, sellerId, items, subtotal, shipping:0, total:subtotal, shippingAddress:buyer.address, paymentId:payment.id, status:'PAGADA', sellerResponse:'', deliveryDate:'', deliveryTime:'', createdAt:new Date().toISOString(), updatedAt:new Date().toISOString()}; orders.push(o); created.push(o); AuditService.log({userId:buyerId,action:'ORDER_CREATED',module:'ORDERS',entityType:'ORDER',entityId:o.id,description:`Orden ${o.id} creada`}); NotificationService.create({recipientId:sellerId,type:'NEW_ORDER',title:'Nueva compra',message:`${buyer.username} realizó una compra. Orden: ${o.id}`,orderId:o.id,actorId:buyerId}); }); StorageService.saveOrders(orders); const products=StorageService.getProducts(); cart.items.forEach(i=>{ const p=products.find(x=>x.id===i.productId); if(p){p.stock-=i.quantity; if(p.stock<=0)p.status='Agotado'; p.updatedAt=new Date().toISOString();} }); StorageService.saveProducts(products); CartService.clear(buyerId); return {payment, orders:created}; };
  const sellerResponse = (sellerId, orderId, data) => { const orders=all(); const o=orders.find(x=>x.id===orderId&&x.sellerId===sellerId); if(!o) throw Error('Orden no encontrada.'); o.status='CONFIRMADA'; o.sellerResponse=data.message; o.deliveryDate=data.deliveryDate; o.deliveryTime=data.deliveryTime; o.updatedAt=new Date().toISOString(); StorageService.saveOrders(orders); AuditService.log({userId:sellerId,action:'SELLER_RESPONSE_CREATED',module:'NOTIFICATIONS',entityType:'ORDER',entityId:orderId,description:`Vendedor indicó entrega para ${data.deliveryDate} ${data.deliveryTime}`}); NotificationService.create({recipientId:o.buyerId,type:'ORDER_CONFIRMED',title:`Tu pedido ${orderId} ha sido confirmado`,message:data.message,orderId,actorId:sellerId}); };
  const updateStatus = (userId, orderId, status) => { const orders=all(); const o=orders.find(x=>x.id===orderId); o.status=status; o.updatedAt=new Date().toISOString(); StorageService.saveOrders(orders); AuditService.log({userId,action:'ORDER_UPDATED',module:'ORDERS',entityType:'ORDER',entityId:orderId,description:`Orden ${orderId} cambió a ${status}`}); };
  const trace = id => AuditService.byEntity(id).concat(NotificationService.byOrder(id).map(n=>({id:n.id,userId:n.recipientId,action:'NOTIFICATION',module:'NOTIFICATIONS',entityId:id,description:n.title+' - '+n.message,timestamp:n.createdAt}))).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
  return {all, find, checkout, sellerResponse, updateStatus, trace};
})();
